### ISSUE TITLE
Source repo URL link is broken

### ISSUE THREAD

**Issue by mekza** [thelabnyc/django-oscar-bundles#1]
It would be nice to replace `https://github.com/thelabnyc/django-oscar-bundles` by `https://gitlab.com/thelabnyc/django-oscar/django-oscar-bundles`.

**Comment by bufke** [comment]
Ah yes - the correct link should be `https://gitlab.com/thelabnyc/django-oscar/django-oscar-bundles` looks liked the repo go moved at some point to a sub group.

**Comment by mekza** [comment]
Thank you for your quick response!

**Comment by bufke** [comment]
Updated link in github description
Submitted for review https://gitlab.com/thelabnyc/django-oscar/django-oscar-bundles/merge_requests/4
